Add contact
k-zhdanova/project-CodeJedi pull request #6
Opened 2023-12-19 20:26 UTC by KomrakovaAnna

2023-12-19 20:29 UTC, KomrakovaAnna commented
![](https://github.trello.services/images/mini-trello-icon.png) [Додавання (основних полів) контактів до книги контактів](https://trello.com/c/c0ADHDOb/7-%D0%B4%D0%BE%D0%B4%D0%B0%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B8%D1%85-%D0%BF%D0%BE%D0%BB%D1%96%D0%B2-%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D1%96%D0%B2-%D0%B4%D0%BE-%D0%BA%D0%BD%D0%B8%D0%B3%D0%B8-%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D1%96%D0%B2)

2023-12-19 21:03 UTC, k-zhdanova requested changes
Все супер, декілька маленьких правок. 

І ще прохання, прибери будь ласка зайві переноси
<img width="891" alt="Screenshot 2023-12-19 at 23 03 15" src="https://github.com/k-zhdanova/project-CodeJedi/assets/104555497/b46c08d9-82c9-47dc-91cc-29556d03b077">

2023-12-19 21:03 UTC, k-zhdanova commented on cli_interface.py
> +            print("Name is required. Input name to add a contact")
Краще тут не print використовувати, а raise <Error>
Або можна зараз додати клас для помилок, або поки що просто: 
`raise ValueError("Name is required. Input name to add a contact")`

Потім в окремій тасці створимо клас для кастомних помилок

Краще кидати ексепшени, бо тоді ми зможемо обробляти усі помилки в одному місці (напр. стилізувати якось)

Тобто в main.py, де у нас вже є блок try ... except додати:
`except ValueError as error:
            print(error)
            continue`

2023-12-19 21:03 UTC, k-zhdanova commented on cli_interface.py
> +            self.phone = input("Input phone: ")
Тут не треба в self додавати записи. Ці поля не відносяться до поточного класу 
Використовуй просто локальні змінні name, phone і т.д.

2023-12-20 04:20 UTC, k-zhdanova approved these changes

2023-12-20 04:20 UTC, merged